use("group5-ecommerce");

db.product.deleteMany({});

db.product.insertMany([
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb39"),
    barcode: "",
    productName: "อกไก่ปั่น รสออริจินัล",
    flavor: "ออริจินัล",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 50,
    unit: "ml",
    unitPrice: 100,
    stockQty: 35,
    isActive: true,
    productDescription: "อกไก่ปั่นพร้อมดื่ม รสออริจินัล",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb39"),
    barcode: "",
    productName: "อกไก่ปั่น รสสตรอว์เบอร์รี",
    flavor: "สตรอว์เบอร์รี",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 50,
    unit: "ml",
    unitPrice: 100,
    stockQty: 57,
    isActive: true,
    productDescription: "อกไก่ปั่นพร้อมดื่ม รสสตรอว์เบอร์รี หอมอร่อย",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb39"),
    barcode: "",
    productName: "อกไก่ปั่น รสกล้วย",
    flavor: "กล้วย",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 50,
    unit: "ml",
    unitPrice: 100,
    stockQty: 63,
    isActive: true,
    productDescription: "อกไก่ปั่นพร้อมดื่ม รสกล้วย หอมละมุนกลิ่นกล้วย",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb39"),
    barcode: "",
    productName: "อกไก่ปั่น รสช็อกโกแลต",
    flavor: "ช็อกโกแลต",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 50,
    unit: "ml",
    unitPrice: 100,
    stockQty: 30,
    isActive: true,
    productDescription: "อกไก่ปั่นพร้อมดื่ม รสช็อกโกแลต เข้มข้น ดื่มง่าย",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb3a"),
    barcode: "",
    productName: "น้ำผลไม้ Green Vitality",
    flavor: "Green Vitality",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 250,
    unit: "ml",
    unitPrice: 100,
    stockQty: 54,
    isActive: true,
    productDescription:
      "น้ำผลไม้รสชาติสดชื่น ดื่มง่าย หอมธรรมชาติจากแอปเปิ้ลเขียว ผสานความสดของแตงกวา เซเลอรี่ และเลมอน",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb3a"),
    barcode: "",
    productName: "น้ำผลไม้ Sunrise Shield",
    flavor: "Sunrise Shield",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 250,
    unit: "ml",
    unitPrice: 100,
    stockQty: 60,
    isActive: true,
    productDescription:
      "น้ำผักผลไม้สกัดเย็นสูตรเสริมภูมิคุ้มกัน รสสดชื่นจากส้มและแครอท ผสานขิงและขมิ้น ช่วยเติมวิตามินเอและซีสูง ดื่มง่าย สดชื่น ไม่มีน้ำตาล",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb3a"),
    barcode: "",
    productName: "น้ำผลไม้ Beetroot Glow",
    flavor: "Beetroot Glow",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 250,
    unit: "ml",
    unitPrice: 100,
    stockQty: 24,
    isActive: true,
    productDescription:
      "น้ำบีทรูทสกัดเย็นเพื่อผิวเปล่งปลั่ง ผสานแอปเปิ้ลแดงและเลมอน รสหวานธรรมชาติ ดื่มง่าย อุดมด้วยใยอาหารและสารต้านอนุมูลอิสระ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb3a"),
    barcode: "",
    productName: "น้ำผลไม้ Charcoal Lemonade",
    flavor: "Charcoal Lemonade",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 250,
    unit: "ml",
    unitPrice: 100,
    stockQty: 21,
    isActive: true,
    productDescription:
      "เลมอนเนดผสมชาร์โคลสูตรดีท็อกซ์ รสเปรี้ยวหวานสดชื่นจากน้ำเลมอนและน้ำผึ้งธรรมชาติ ช่วยรีเฟรชร่างกาย ดื่มแล้วรู้สึกเบาสบาย",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb3a"),
    barcode: "",
    productName: "น้ำผลไม้ Watermelon Flush",
    flavor: "Watermelon Flush",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 250,
    unit: "ml",
    unitPrice: 100,
    stockQty: 45,
    isActive: true,
    productDescription:
      "น้ำแตงโมสกัดเย็นสดชื่น ผสมแตงกวาและมิ้นต์ ช่วยเติมความสดชื่น คลายร้อน และเติมน้ำให้ร่างกาย เหมาะสำหรับดื่มระหว่างวัน",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb3a"),
    barcode: "",
    productName: "น้ำผลไม้ Sweet Greens",
    flavor: "Sweet Greens",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 250,
    unit: "ml",
    unitPrice: 100,
    stockQty: 13,
    isActive: true,
    productDescription:
      "น้ำผักผลไม้สีเขียวรสหวานดื่มง่าย จากแอปเปิ้ล กีวี่ และผักโขม อุดมด้วยวิตามินซีและเค",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb3a"),
    barcode: "",
    productName: "น้ำผลไม้ Celery Pure",
    flavor: "Celery Pure",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 250,
    unit: "ml",
    unitPrice: 100,
    stockQty: 32,
    isActive: true,
    productDescription:
      "น้ำเซเลอรี่สกัดเย็น 100% รสธรรมชาติ เหมาะสำหรับสายคลีนและดีท็อกซ์ ช่วยเสริมสมดุลร่างกาย ดื่มง่ายในตอนเช้า",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb3a"),
    barcode: "",
    productName: "น้ำผลไม้ Citrus Kick",
    flavor: "Citrus Kick",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 250,
    unit: "ml",
    unitPrice: 100,
    stockQty: 27,
    isActive: true,
    productDescription:
      "น้ำผลไม้รสเปรี้ยวสดชื่นจากเกรปฟรุต ส้ม และเลมอน เพิ่มความซ่าเล็กน้อยจากพริกคาเยน อุดมด้วยวิตามินซีสูง ช่วยปลุกความสดชื่น",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb3a"),
    barcode: "",
    productName: "น้ำผลไม้ Ruby Antioxidant",
    flavor: "Ruby Antioxidant",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 250,
    unit: "ml",
    unitPrice: 100,
    stockQty: 45,
    isActive: true,
    productDescription:
      "น้ำผลไม้สีแดงเข้มจากทับทิม แอปเปิ้ล และองุ่น อุดมด้วยสารต้านอนุมูลอิสระ รสหวานธรรมชาติ เหมาะสำหรับดูแลผิวและสุขภาพ",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    categoryId: ObjectId("69cfcc6687666d6fcd59cb3a"),
    barcode: "",
    productName: "น้ำผลไม้ Coconut Recharge ",
    flavor: "Coconut Recharge ",
    brand: "Juicy Health",
    container: "ขวด",
    volume: 250,
    unit: "ml",
    unitPrice: 100,
    stockQty: 54,
    isActive: true,
    productDescription:
      "น้ำมะพร้าวผสมสับปะรด เติมความสดชื่นและเกลือแร่ ช่วยรีเฟรชร่างกายหลังออกกำลังกาย รสชาติหวานธรรมชาติ ดื่มแล้วสดชื่นทันที",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);
